name: "hello workflow"
on:
  push:
    branches:
     - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
     - name: "Say Hello World"
       run: echo "Hello World"

     - name: "Test Project"
       run: |
        echo "How are you?"
        echo "I am fine"